version: 2.1

orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.1.1

jobs:
  build_macos:
    macos:
      xcode: "14.3.0"  # Latest stable Xcode version
    resource_class: macos.m1.medium.gen2  # M1 for better performance
    steps:
      - checkout

      # Install Node.js using nvm
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            node --version
            npm --version

      # Install Python and pipenv
      - run:
          name: Install Python
          command: |
            brew install python@3.10
            echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> ~/.bash_profile
            source ~/.bash_profile
            python3 --version
            pip3 --version

      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            brew install pkg-config cairo pango libpng jpeg giflib librsvg

      # Cache node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            npm ci
            pip3 install -r src/python-server/requirements.txt
            pip3 install pyinstaller==5.13.0

      # Save node_modules to cache
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Build the application
      - run:
          name: Build application
          command: npm run make:mac

      # Store artifacts
      - store_artifacts:
          path: out/make
          destination: build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_macos:
          filters:
            branches:
              only: 
                - mac-release  # Only build on mac-release branch