import { app, BrowserWindow, session, ipcMain } from 'electron';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { spawn, execSync } from 'child_process';
import * as fs from 'fs';

// Load environment variables from .env file
const envPath = path.join(__dirname, '../../.env');
console.log('Loading environment variables from:', envPath);
dotenv.config({ path: envPath });
let pythonProcess: any = null;

// Debug: Log loaded environment variables
console.log('Environment variables loaded:', {
  SUPABASE_URL: process.env.REACT_APP_SUPABASE_URL ? '***' : 'NOT FOUND',
  SUPABASE_ANON_KEY: process.env.REACT_APP_SUPABASE_ANON_KEY ? '***' : 'NOT FOUND',
  NODE_ENV: process.env.NODE_ENV || 'development'
});

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Define allowed environment variables
const ALLOWED_ENV_KEYS = [
  'REACT_APP_SUPABASE_URL',
  'REACT_APP_SUPABASE_ANON_KEY',
  'NODE_ENV'
];

// Create a safe environment object
const env = ALLOWED_ENV_KEYS.reduce((acc, key) => {
  if (process.env[key]) {
    acc[key] = process.env[key]!;  // Non-null assertion since we checked it exists
  }
  return acc;
}, {} as Record<string, string>);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

/**
 * Starts the python server
 */
function startPythonServer() {
  const isDev = process.env.NODE_ENV === 'development';
  const pythonPath = isDev 
    ? path.join(__dirname, '../../src/python-server/venv/Scripts/python.exe')
    : path.join(process.resourcesPath, 'python', 'python-server.exe');

  console.log('Python server path:', pythonPath);
  
  if (!fs.existsSync(pythonPath)) {
    console.error('Python server executable not found at:', pythonPath);
    return;
  }

  const serverPath = isDev
    ? path.join(__dirname, '../../src/python-server/app.py') // Directly run the script using the py interpreter
    : path.join(process.resourcesPath, 'wsgi.py');

  if (isDev){
    // if dev, need to run the server .py script with the py interpreter installed in the venv
    pythonProcess = spawn(pythonPath, [serverPath], {
      stdio: 'pipe',
      shell: true,
      env: {
        ...process.env,  // Keep existing env vars
        FLASK_ENV: 'development',
        FLASK_DEBUG: '1'
      }
    });
  }else{
    // check platform
    const runFlask = {
      darwin: `open -gj "${pythonPath}}" --args`,
      linux: `${pythonPath}`,
      win32: `start ${pythonPath}`,
      aix: '',
      sunos: '',
      cygwin: '',
      freebsd: '',
      openbsd: '',
      android: '',
      haiku: '',
      netbsd: '',      
    }[process.platform];

    // if prod, only need to run the .exe file which has an interpreter packaged with pyinstaller
    pythonProcess = spawn(`${runFlask}`, {
      stdio: 'pipe',
      shell: true,
      env: {
        ...process.env,  // Keep existing env vars
        FLASK_ENV: 'production',
        FLASK_DEBUG: '1'
      }
    });
  }

  

  pythonProcess.stdout.on('data', (data: Buffer) => {
    console.log(`Python Server: ${data}`);
  });

  pythonProcess.stderr.on('data', (data: Buffer) => {
    console.error(`Python Server Error: ${data}`);
  });

  pythonProcess.on('close', (code: number) => {
    console.log(`Python server process exited with code ${code}`);
  });
}

/**
 * Creates the main electron browser window
 */
const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1280,
    width: 800,
    minWidth: 1024,
    minHeight: 768,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,  // Disable Node.js integration in the renderer
      contextIsolation: true,  // Enable context isolation for security
      webviewTag: true,        // Enable webview tag
      webSecurity: true,       // Enable web security
      sandbox: true,           // Enable sandbox for better security
      // In Electron 12+, remote module is disabled by default
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.maximize();
  // temporary -- remove for prod
  mainWindow.webContents.openDevTools();

  // Add this back for prod -- don't want dev tools menu opening in prod
  /**
   * if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
   */
  
};

/**
 * IPC handler to get environment variables
 */
ipcMain.handle('get-env', (event, key: string) => {
  if (ALLOWED_ENV_KEYS.includes(key)) {
    return process.env[key];
  }
  console.warn(`Attempted to access unauthorized environment variable: ${key}`);
  return null;
});

/**
 * This method will be called when Electron has finished
 * initialization and is ready to create browser windows.
 * Some APIs can only be used after this event occurs.
 */
app.whenReady().then(() => {
  // Set Content Security Policy
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const csp = [
      "default-src 'self'",
      "connect-src 'self' https://*.supabase.co https://otnlburbcvilvzgbjzqi.supabase.co",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob:",
      "font-src 'self' data:",
      "frame-src 'self'"
    ].join('; ');

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [csp]
      }
    });
  });

  // Start Python server
  startPythonServer();

  // Clear cache before creating window
  session.defaultSession.clearCache().then(() => {
    createWindow();
  });
});

/**
 * Quit when all windows are closed, except on macOS. There, it's common
 * for applications and their menu bar to stay active until the user quits
 * explicitly with Cmd + Q.
 */
app.on('window-all-closed', () => {
  // Stop Python server
  if (pythonProcess) {
    console.log('Stopping Python server...');
    pythonProcess.kill();
  }
  // Quit the electron app
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
